# Generated by Django 4.0.3 on 2022-03-30 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor_name', models.IntegerField(max_length=30)),
                ('donor_email', models.EmailField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_semester', models.IntegerField(max_length=2)),
                ('student_education_dues', models.IntegerField(max_length=2)),
                ('student_details', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donation_amount', models.IntegerField(max_length=10)),
                ('donation_time', models.DateTimeField(auto_now=True)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donation', to='trp_api.donor')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donation', to='trp_api.student')),
            ],
        ),
    ]
