# Generated by Django 4.0.3 on 2022-03-31 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trp_api', '0002_alter_donor_donor_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='donation_time',
            field=models.DateTimeField(auto_now=True, verbose_name='%Y-%m-%d %H:%M:%S'),
        ),
    ]
