# Generated by Django 4.0.3 on 2022-04-05 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trp_api', '0006_alter_donation_donation_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='donation_amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_education_dues',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_semester',
            field=models.IntegerField(),
        ),
    ]
