# Generated by Django 2.2.13 on 2022-04-19 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trp_api', '0010_auto_20220419_1332'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='by_user',
            new_name='user',
        ),
    ]
