# Generated by Django 4.0.4 on 2022-05-11 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trp_api', '0012_alter_donation_id_alter_student_id_alter_userinfo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='donation_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
